oauth2:
  naver:
    client-id: ${OAUTH2_NAVER_CLIENT_ID}
    client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
    redirect-uri: ${OAUTH2_NAVER_REDIRECT_URI}
    authorization-code-uri: https://nid.naver.com/oauth2.0/authorize
    state: "WHAT-IS-THIS"
    scope: