oauth2:
  google:
    redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI}
    client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
    authorization-code-uri: "https://accounts.google.com/o/oauth2/v2/auth"
    scope:
      # - openid
      - profile
      - email
