oauth2:
  kakao:
    rest-api-key: ${OAUTH2_KAKAO_REST_API_KEY}
    client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
    client-id: ${OAUTH2_KAKAO_CLIENT_ID}
    authorization-code-uri: https://kauth.kakao.com/oauth/authorize
    redirect-uri: http://localhost:3000/oauth2/redirected/kakao
    scope:
      # - openid
      - profile_nickname
      - profile_image
      - account_email
      - gender