server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /
spring:
  datasource:
    url: ${MARIADB_URL}/${MARIADB_NAME}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true