server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /
spring:
  datasource:
    url: ${MARIADB_URL}/${MARIADB_NAME}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          # https://accounts.google.com/.well-known/openid-configuration
          google:
            redirect-uri: http://localhost:3000/oauth2/redirected/google
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
          naver:
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-name: NAVER_LOGIN_API
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope:
              - profile
              - email
          # 참고: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app
          github:
            client-id: ${OAUTH2_GIT_CLIENT_ID}
            client-name: social_github
            client-secret: ${OAUTH2_GIT_CLIENT_SECRET}
            redirect-uri: http://localhost:8081/login/oauth2/code/github
            scope:
              - read:User
              - User:email
          kakao:
            client-id: ${OAUTH2_KAKAO_REST_API_KEY}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            client-name: ${OAUTH2_KAKAO_CLIENT_ID}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            scope:
              - openid
              - profile_nickname
              - profile_image
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          # https://kauth.kakao.com/.well-known/openid-configuration
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            # openid connect -> O
            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            # openid connect -> X
            # User-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: sub